# Generated by Django 4.1 on 2022-09-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcategory", old_name="category", new_name="subcategory",
        ),
        migrations.CreateModel(
            name="SubSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.TextField(unique=True)),
                (
                    "subsubcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.subcategory",
                    ),
                ),
            ],
        ),
    ]
