# Generated by Django 4.1 on 2022-09-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_rename_category_subcategory_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider", name="text1", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="slider", name="title", field=models.TextField(blank=True),
        ),
    ]
